services:
  endfield-auto-check-in:
    build:
      context: .
      dockerfile: Dockerfile
    image: endfield-auto-check-in
    container_name: endfield-auto-check-in
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
      - NODE_ENV=production
